# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 13 0 0 0"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Create secrets.yml
      run: |
        echo "notion-token: $NOTION" >> secrets.yml
        echo -e "\nbot-token: $SLACK" >> secrets.yml
      env:
        NOTION: ${{ secrets.NOTION }}
        SLACK: ${{ secrets.SLACK }}
    - name: Check secrets.yml
      run: |
        cat secrets.yml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run main.py
      run: |
        python main.py
